---
title: "Interface com RSiconfi"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(rsiconfi)
library(networkD3)
library(ggplot2)
library(viridis)
library(readr)
library(dplyr)

state_machine<-1

glossario_siconfi <- read_delim("glossario_siconfi.csv", 
     ";", escape_double = FALSE, trim_ws = TRUE)


text_header_chart<- function(chart, estado){
  
  text_header<- data.frame(l=1,c=1)
  text_header[1,1]<- "Apresentação"
  text_header[2,1]<- "Exemplo de análise do relatório selecionado"
  text_header[3,1]<- "Exemplo de dados do relatório selecionado"
  
  text_header[chart,estado]
}

text_chart<- function(chart, estado, linha){
  
  text_line<- data.frame(l=1,c=1)
  if (chart==1){
    
    text_line[1,1]<- "Bemvindo. A partir daqui você terá a possibilidade de construir dinamicamente consulta que consumirá dados do SICONFI" 
    text_line[1,2]<-"Logo ao lado esquerdo você vê um menu que oferece as opções dos principais tipos de relatórios possíveis"
    text_line[1,3]<-"Ao selecionar uma das opções de relatórios será exibido ao lado direito um exemplo de análise dos dados associados à opção, na primeira aba, bem como os dados que geraram essa análise, na segunda aba"

  }
  
  text_line[estado,linha]

}

generate_graph<- function(chart, estado, opcao){
  
  if(chart==1){
    if(estado == 1){ #relatórios iniciais
      if (opcao==1){#Receitas orçamentárias
        
        df_rec <<- rsiconfi::get_dca(2018,"I-C","1")
        
        
        df_rec_trabalho<-
          df_rec %>% 
          #filter(stringr::str_starts(cod_conta,"R")) %>%
          filter(coluna == "Receitas Brutas Realizadas") %>%
          mutate(nivel_0 = cod_conta =="TotalReceitas" ) %>%
          mutate(nivel_1= (stringr::str_ends(cod_conta,".0.0.0.00.0.0"))) %>%
          mutate(nivel_2= ((stringr::str_sub(cod_conta,5,5)!= "0") & (stringr::str_ends(cod_conta,"0.0.00.0.0")))) %>%
          mutate(nivel_3= ((stringr::str_sub(cod_conta,7,7)!= "0") & (stringr::str_ends(cod_conta,"0.00.0.0")))) %>%
          filter(nivel_0 | nivel_1 | nivel_2 | nivel_3) %>%
          mutate(pai = case_when(
            nivel_1 ~ "TotalReceitas",
            nivel_2 ~ paste0(stringr::str_sub(cod_conta,1,3), ".0.0.0.00.0.0"),
            nivel_3 ~ paste0(stringr::str_sub(cod_conta,1,5), ".0.0.00.0.0")
          )) %>%
          mutate (source = row_number() -1)
        
        
        graph<-
        df_rec_trabalho%>%
          filter(nivel_2==1)%>%
          mutate(conta =  stringr::str_sub(conta, 18,str_length(conta)))%>%
          select(conta, valor) %>%
          mutate(conta = reorder(conta, valor)) %>%
          ggplot(aes(x=conta, y= valor/10^6)) +
          geom_col(fill= "#eec237") +
          theme_light() +
          theme(
            strip.text =  element_blank(),
            axis.text.x =  element_text(angle = 90, hjust = 1),
            panel.grid = element_blank()  )+
          labs(
            y = "Valor em R$ milhões",
            x=  NULL,
            fill = ""  )+
          scale_y_continuous(labels=function(x) format(x, big.mark = ".", scientific = FALSE))+
          #facet_grid(instituicao~.,  space = "free_y") +
          coord_flip()
        
        list(graph, df_rec)
        
        
      }
      
    }
  }
  
}

```

Inputs {.sidebar}
-------------------------------------

```{r}
radioButtons("topico",label = "Escolha o tipo de consulta", choices = (glossario_siconfi%>%
    select(topico))$topico)
```


Column {data-width=200}
-----------------------------------------------------------------------

### `r text_header_chart(1,state_machine)`

`r text_chart(1,state_machine, 1)`
`r HTML("</BR>")`
`r text_chart(1,state_machine,2)`
`r HTML("</BR>")`
`r text_chart(1,state_machine,3)`

```{r}
renderText({
  (glossario_siconfi%>%
    filter(topico==input$topico) %>%
    select(explicacao))$explicacao
  
})
```



Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

### `r text_header_chart(2,state_machine)`

```{r}


renderPlot({
  
  id_opcao<- 
    (glossario_siconfi%>%
    filter(topico==input$topico)%>%
    select(id))$id
  
  #list_graph<-generate_graph(1,1,1)
  list_graph<-generate_graph(1,1,id_opcao)
  
  raw_data<<- list_graph[[2]]
  
  list_graph[[1]]
  

})


```

### `r text_header_chart(3,state_machine)`

```{r}
library(DT)
renderDataTable({
  
  DT::datatable(
    
  raw_data,
    rownames = FALSE,
  fillContainer = TRUE,
  
  extensions = 'Buttons', options = list(
    dom = 'Bfrtip',
    buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
  )
 )  
    
  
})

```

