---
title: "Interface com RSiconfi"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}

library(flexdashboard)
library(rsiconfi)
library(shiny)
library(networkD3)
library(ggplot2)
library(viridis)
library(readr)
library(dplyr)
library(shinyjs)
library(kableExtra)
library(purrr)
library(readxl)
library(readr)


show_graph<<-TRUE
show_data<<- TRUE

load("dados_cluster.RData")

municipios_IBGE<- 
  municipios_IBGE %>%
  mutate(pop_estimada = as.numeric(stringr::str_remove_all(pop_estimada,","))) 

RELATORIO_DTB_BRASIL_MUNICIPIO <- read_excel("RELATORIO_DTB_BRASIL_MUNICIPIO.xls")

#dados_municipios_ibge_2010_2017 <- read_excel("dados_municipios_ibge_2010_2017.xls")

ibge_pib_mun <- read_delim("ibge_pib_mun.csv", 
    ";", escape_double = FALSE, col_types = cols(X1 = col_skip(), 
        cod_mun = col_character()), locale = locale(encoding = "LATIN1"), 
    trim_ws = TRUE)


# ibge_pib_mun<- 
#   dados_municipios_ibge_2010_2017 %>%
#   filter(Ano ==2017) %>%
#   select(`Código do Município`,`Produto Interno Bruto per capita, 
# a preços correntes
# (R$ 1,00)`,`Produto Interno Bruto, 
# a preços correntes
# (R$ 1.000)`,`Atividade com maior valor adicionado bruto`)
# 
# names(ibge_pib_mun)<- c("cod_mun", "PIB_PC" , "PIB_total", "atvidade_economica")
# 
# write.csv2(ibge_pib_mun, "ibge_pib_mun.csv")

faixas_ibge<-c("Até 2.000 pessoas", "De 2.001 a 5.000 pessoas","De 5.001 a 10.000 pessoas", "De 10.001 a 20.000 pessoas", "De 20.001 a 50.000 pessoas", "De 50.001 a 100.000 pessoas", "De 100.001 a 500.000 pessoas","Mais de 500.000 pessoas")

ibge_pib_mun<-
ibge_pib_mun %>%
  arrange(desc(PIB_PC)) %>%
  mutate(pos_PC = seq(1,NROW(ibge_pib_mun),1)) %>%
  arrange(desc(PIB_total)) %>%
  mutate(pos_PIB = seq(1,NROW(ibge_pib_mun),1))


glossario_siconfi <- read_delim("glossario_siconfi.csv", 
     ";", escape_double = FALSE, trim_ws = TRUE)

instrucoes <- read_delim("instrucoes.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

state_element <- read_delim("state_element.csv", 
    ";", escape_double = FALSE, trim_ws = TRUE)

state_button_next <- read_delim("state_button_next.csv", 
    ";", escape_double = FALSE, col_types = cols(X4 = col_skip()), 
    trim_ws = TRUE)

contas<-rsiconfi::get_account_dca(2018,"I-E",1)

hidden(
  div(id = "tipo_cons_mun", radioButtons("tipo_cons_mun", label ="Informe o filtro para municípios", choices = c("Escolher de uma lista", "Todos de uma ou mais UFs","Por faixa populacional"), selected = "Escolher de uma lista"))
  
         )

get_lista_atividades<- function(){
  
  (ibge_pib_mun%>%
    group_by(atvidade_economica) %>%
    summarise(
      total = sum(PIB_total)
    ) %>%
    ungroup() %>%
    mutate(atvidade_economica = reorder(atvidade_economica, total)) %>%
    arrange(desc(atvidade_economica)) %>%
    select(atvidade_economica))$atvidade_economica
  
}


get_lista_mesoregioes<- function(){
  
  (RELATORIO_DTB_BRASIL_MUNICIPIO%>%
    arrange(Nome_Mesorregião) %>%
    distinct(Nome_Mesorregião))$Nome_Mesorregião
    
}


get_lista_instituicao<- function(opcao){
  
  if(opcao$escopo == "Governo Federal"){
    lista_instituicao<-1
  } else if(opcao$escopo == "Estados"){
    
    cod_uf<-   
      (municipios_IBGE%>%   
         filter(uf %in% opcao$uf) %>%   
         distinct(cod_uf))$cod_uf
    
    
    lista_instituicao <- cod_uf
    
  } else if (opcao$escopo == "Municípios"){
    
    if (opcao$tipo_cons_mun=="Escolher de uma lista"){
      cod_mun<- 
        (municipios_IBGE%>%
           filter(nome_municipio %in% opcao$municipio) %>%
           select(cod_mun))$cod_mun
      
      lista_instituicao <- cod_mun
      
      
    } else if (opcao$tipo_cons_mun=="Por faixa populacional - quartis"){
      
      IBGE<- 
        municipios_IBGE %>%
        filter(!is.na(pop_estimada)) %>%
        mutate(pop_estimada = as.numeric(stringr::str_remove_all(pop_estimada,","))) 
      
      mun_q1<-
        (IBGE %>%
           filter(pop_estimada<=quantile(IBGE$pop_estimada, 0.25, na.rm = TRUE)))$cod_mun
      
      mun_q2<-
        (IBGE %>%
           filter(pop_estimada>quantile(IBGE$pop_estimada, 0.25, na.rm = TRUE),
                  pop_estimada<=quantile(IBGE$pop_estimada, 0.5, na.rm = TRUE)))$cod_mun
      
      mun_q3<-
        (IBGE %>%
           filter(pop_estimada>quantile(IBGE$pop_estimada, 0.5, na.rm = TRUE),
                  pop_estimada<=quantile(IBGE$pop_estimada, 0.75, na.rm = TRUE)))$cod_mun
      
      mun_q4<-
        (IBGE %>%
           filter(pop_estimada>quantile(IBGE$pop_estimada, 0.75, na.rm = TRUE)))$cod_mun
      
      #"Primeiro quartil", "Segundo quartil","Terceiro quartil", "Quarto quartil"
      
      lista_instituicao<- c(numeric())
      if ("Primeiro quartil" %in% opcao$mun_pop){
        lista_instituicao<- c(lista_instituicao,mun_q1)
      }
      
      if ("Segundo quartil" %in% opcao$mun_pop){
        lista_instituicao<- c(lista_instituicao,mun_q2)
      }
      
      if ("Terceiro quartil" %in% opcao$mun_pop){
        lista_instituicao<- c(lista_instituicao,mun_q3)
      }
      
      if ("Quarto quartil" %in% opcao$mun_pop){
        lista_instituicao<- c(lista_instituicao,mun_q4)
      }
      
    } else if (opcao$tipo_cons_mun=="Por faixa populacional - grupos ibge"){
      
      IBGE<- 
        municipios_IBGE %>%
        filter(!is.na(pop_estimada)) %>%
        mutate(pop_estimada = as.numeric(stringr::str_remove_all(pop_estimada,","))) 
      
      mun_f1<-
        (IBGE %>%
           filter(pop_estimada<=2000))$cod_mun
      
      mun_f2<-
        (IBGE %>%
           filter(pop_estimada>2001,
                  pop_estimada<=5000))$cod_mun
      
      mun_f3<-
        (IBGE %>%
           filter(pop_estimada>5001,
                  pop_estimada<=10000))$cod_mun
      
      mun_f4<-
        (IBGE %>%
           filter(pop_estimada>10001,
                  pop_estimada<=20000))$cod_mun
      
      mun_f5<-
        (IBGE %>%
           filter(pop_estimada>20001,
                  pop_estimada<=50000))$cod_mun
      
      mun_f6<-
        (IBGE %>%
           filter(pop_estimada>50001,
                  pop_estimada<=100000))$cod_mun
      
      mun_f7<-
        (IBGE %>%
           filter(pop_estimada>100001,
                  pop_estimada<=500000))$cod_mun

      mun_f8<-
        (IBGE %>%
           filter(pop_estimada>500000))$cod_mun

            

      #"Primeiro quartil", "Segundo quartil","Terceiro quartil", "Quarto quartil"
      
      
      
      
      lista_instituicao<- c(numeric())
      if (faixas_ibge[1] %in% opcao$mun_pop_faixa){
        lista_instituicao<- c(lista_instituicao,mun_f1)
      }
      
      if (faixas_ibge[2] %in% opcao$mun_pop_faixa){
        lista_instituicao<- c(lista_instituicao,mun_f2)
      }

      if (faixas_ibge[3] %in% opcao$mun_pop_faixa){
        lista_instituicao<- c(lista_instituicao,mun_f3)
      }
      if (faixas_ibge[4] %in% opcao$mun_pop_faixa){
        lista_instituicao<- c(lista_instituicao,mun_f4)
      }
      if (faixas_ibge[5] %in% opcao$mun_pop_faixa){
        lista_instituicao<- c(lista_instituicao,mun_f5)
      }
      if (faixas_ibge[6] %in% opcao$mun_pop_faixa){
        lista_instituicao<- c(lista_instituicao,mun_f6)
      }
      if (faixas_ibge[7] %in% opcao$mun_pop_faixa){
        lista_instituicao<- c(lista_instituicao,mun_f7)
      }
      
      if (faixas_ibge[8] %in% opcao$mun_pop_faixa){
        lista_instituicao<- c(lista_instituicao,mun_f8)
      }
            

    } else if (opcao$tipo_cons_mun=="Todos de uma ou mais UFs"){
      
      cod_uf<-   
        (municipios_IBGE%>%   
           filter(uf %in% opcao$mun_uf) %>%   
           distinct(cod_uf))$cod_uf
      
      print(opcao)
      lista_instituicao <- cod_uf
      
      
    } else if (opcao$tipo_cons_mun=="Por Mesoregião"){
      
      lista_instituicao<-   
        (RELATORIO_DTB_BRASIL_MUNICIPIO %>%
        filter(Nome_Mesorregião %in% opcao$mun_meso) %>%
        select(`Código Município Completo`))$  `Código Município Completo`
      
      
    } else if (opcao$tipo_cons_mun=="Por posição PIB per-capita"){
      
      print(opcao$mun_pib_pc)
      
      lista_instituicao<-   
        (ibge_pib_mun %>%
        filter(between(pos_PC,opcao$mun_pib_pc[1],opcao$mun_pib_pc[2])))$cod_mun
      
      
    } else if (opcao$tipo_cons_mun=="Por posição PIB total"){
      
      print(opcao$mun_pib_total)
      
      lista_instituicao<-   
        (ibge_pib_mun %>%
        filter(between(pos_PIB,opcao$mun_pib_total[1],opcao$mun_pib_total[2])))$cod_mun
    
    } else if (opcao$tipo_cons_mun=="Por principal atividade econômica"){
      
      print(opcao$mun_atv_eco)
      
      lista_instituicao<-   
        (ibge_pib_mun %>%
        filter(atvidade_economica %in% opcao$mun_atv_eco ))$cod_mun
    
    }  else if (opcao$tipo_cons_mun=="Por agrupamento econômico"){
      
      print(opcao$mun_grp_eco)
      
        cod_mun_cluster<- 
        (municipios_IBGE%>%
           filter(nome_municipio %in% opcao$mun_grp_eco) %>%
           select(cod_mun))$cod_mun   
        
        cluster_sel<-
        (dados_cluster %>%
        filter(cod_mun == cod_mun_cluster) %>%
          select(cluster))$cluster
        
        lista_instituicao<-
        (dados_cluster %>%
        filter(cluster == cluster_sel) %>%
          select(cod_mun))$cod_mun

    }
  
  lista_instituicao
  }
  
}

set_next_state<- function(current_state,a_button){
  
  
  
  #hide the element associated with the current state
  element<-
    (state_element %>%
    filter(state==current_state)%>%
    select(element))$element
  
  
  
  hide(element)
  
  
  
  
  
  #identify the next state
  
  special_state<- FALSE
  
  full_state<-
  state_button_next %>%
    filter(state == current_state,
           button == a_button)
  
  
  
  # full_state<-
  # (state_button_next %>%
  #   filter(state == 2,
  #          button == "A") %>%
  #   select(next_state))$next_state
  
  print("full_state")
  print(full_state)
  
  if(NROW(full_state)>0){
    
    for (i in 1:NROW(full_state)){
      
      condition<- eval(parse(text=full_state$condition[i]))
      
      if (condition){break()}
      
    }

    
    if (condition){
      next_state_f <- full_state$next_state[i]
      special_state <- TRUE
    }
    
  }
  
  
  if (!special_state  && a_button == "P"){
    
    
    next_state_f<- trunc(as.numeric(current_state)) +1
  }

  if (!special_state && a_button == "A"){
    next_state_f<- trunc(as.numeric(current_state)) - 1
    
  }
  
  
  
  #show the elements and buttons associated with the next state
  df_state_element<-
    state_element %>%
    filter(state==next_state_f)
  
  
  # df_state_element<-
  #   state_element %>%
  #   filter(state==2)
  
  
  element<- df_state_element$element
  button_a<- df_state_element$button_a
  button_p<- df_state_element$button_p
  button_f<- df_state_element$button_f
  
  print("df_state_element")
  print(df_state_element)
  
  #print(next_state_f)
  promise_state<- 
    state_button_next %>%
    filter(state == next_state_f,
           button == "P")
  print("promise_state")
  print(promise_state)
  
  if (NROW(promise_state)>0){
    
    for (i in 1:NROW(promise_state)){
      
      condition<- eval(parse(text=promise_state$condition[i]))
      print(condition)
      
      if (condition){break()}
      
    }

    
    #print(promise_state$condition[1])
    condition<- eval(parse(text=promise_state$condition[i]))
    #print(condition)
    if(condition){
     button_p<-1 
    } 
  }
  
  #if(special_state){button_p<-1}

  updateTextInput(session = session, inputId = "state", value = next_state_f)
  
  show(element)
  
  if(button_a==1){
    show("anterior")
  } else{
    hide("anterior")
  }
  
  if (button_p==1){
    show("proximo")
  } else{
    hide("proximo")
  }
    
  
  
  if (button_f==1){
    show("finalizar")
  } else{
    hide("finalizar")
  }
  


}

generate_graph<- function(opcao){
  
  
  lista_instituicao <- get_lista_instituicao(opcao)
  opcao_uf <- (opcao$tipo_cons_mun=="Todos de uma ou mais UFs" & opcao$escopo == "Municípios")
  
  

  if (opcao$topico==1){#Receitas orçamentárias
    #df_rec <- rsiconfi::get_dca(c(2015,2018),"I-C","1")
    
    

    if (opcao_uf){
      df_rec <- rsiconfi::get_dca_mun_state(opcao$ano,"I-C",lista_instituicao)
      
    } else{
      
      df_rec <- rsiconfi::get_dca(opcao$ano,"I-C",lista_instituicao)
      
    }
    
    
    df_rec_trabalho<-
      df_rec %>%
      #filter(stringr::str_starts(cod_conta,"R")) %>%
      filter(coluna == "Receitas Brutas Realizadas") %>%
      mutate(nivel_0 = cod_conta =="TotalReceitas" ) %>%
      mutate(nivel_1= (stringr::str_ends(cod_conta,".0.0.0.00.0.0"))) %>%
      mutate(nivel_2= ((stringr::str_sub(cod_conta,5,5)!= "0") & (stringr::str_ends(cod_conta,"0.0.00.0.0")))) %>%
      mutate(nivel_3= ((stringr::str_sub(cod_conta,7,7)!= "0") & (stringr::str_ends(cod_conta,"0.00.0.0")))) %>%
      filter(nivel_0 | nivel_1 | nivel_2 | nivel_3) %>%
      mutate(pai = case_when(
        nivel_1 ~ "TotalReceitas",
        nivel_2 ~ paste0(stringr::str_sub(cod_conta,1,3), ".0.0.0.00.0.0"),
        nivel_3 ~ paste0(stringr::str_sub(cod_conta,1,5), ".0.0.00.0.0")
      )) %>%
      mutate (source = row_number() -1) 
    
    instituicao_sel<-
    (df_rec_trabalho %>%
      group_by(instituicao) %>%
      summarise(
        valor = sum(valor)
      ) %>%
      top_n(10, valor))$instituicao
    
    
    
    
    graph<-
      df_rec_trabalho%>%
      filter(nivel_2==1)%>%
      mutate(conta =  stringr::str_sub(conta, 18,str_length(conta)),
             exercicio = as.character(exercicio))%>%
      select(conta, valor, exercicio,instituicao) %>%
      mutate(conta = reorder(conta, valor)) %>%
      filter(instituicao %in% instituicao_sel) %>%
      ggplot(aes(x=conta, y= valor/10^6)) +
      geom_col(fill= "#fdd500") + #
      theme_light() +
      theme(
        #strip.text =  element_blank(),
        axis.text.x =  element_text(angle = 90, hjust = 1),
        panel.grid = element_blank()  )+
      labs(
        y = "Valor em R$ milhões",
        x=  NULL,
        fill = ""  )+
      scale_y_continuous(labels=function(x) format(x, big.mark = ".", scientific = FALSE))+
      facet_wrap(factor(exercicio)+instituicao~.) +
      #facet_grid(unique(conta)+exercicio~., scales =   "free_y")+
      coord_flip()
    
    return(graph)
    
    
  }
  
  if (opcao$topico==2){ #Despesas orçamntárias
    
    if (opcao_uf){
      df_desp <- rsiconfi::get_dca_mun_state(opcao$ano,"I-D",lista_instituicao)
    } else{
      df_desp <- rsiconfi::get_dca(opcao$ano,"I-D",lista_instituicao)
    }
    
    
    #Criar gráfico de sankey
    
    df_desp <-
      df_desp%>%
      filter(coluna %in% opcao$fase)
    
    df_desp <-
      df_desp%>%
      filter(coluna %in% "Despesas Liquidadas")
    
    
    df_desp_trabalho<-
      df_desp %>%
      #filter(stringr::str_starts(cod_conta,"R")) %>%
      #filter(coluna == "Despesas Liquidadas") %>%
      mutate(nivel_0 = cod_conta =="TotalDespesas" ) %>%
      mutate(nivel_1= (stringr::str_ends(cod_conta,"0.00.00.00.00"))) %>%
      mutate(nivel_2= ((stringr::str_sub(cod_conta,5,5)!= "0") & (stringr::str_ends(cod_conta,"00.00.00.00")))) %>%
      mutate(nivel_3= ((stringr::str_sub(cod_conta,7,8)!= "00") & (stringr::str_ends(cod_conta,"00.00.00")))) %>%
      filter(nivel_0 | nivel_1 | nivel_2 | nivel_3  ) %>% #
      mutate(pai = case_when(
        nivel_1 ~ "TotalDespesas",
        nivel_2 ~ paste0(stringr::str_sub(cod_conta,1,3), ".0.00.00.00.00"),
        nivel_3 ~ paste0(stringr::str_sub(cod_conta,1,5), ".00.00.00.00")
      )) %>%
      filter(str_sub(cod_conta,1,2)!="DI")%>%
      mutate (source = row_number() -1)%>% 
      mutate(conta= case_when(
        cod_conta == "TotalDespesas" ~ "Total de despesas liquidadas",
        exercicio == "2018" ~ stringr::str_sub(conta, 16,str_length(conta)),
        exercicio < "2018" ~  stringr::str_sub(conta, 19,str_length(conta))
      ))
    
    instituicao_sel<-
    (df_desp_trabalho %>%
      group_by(instituicao) %>%
      summarise(
        valor = sum(valor)
      ) %>%
      top_n(10, valor))$instituicao
      
    
    graph<-
      df_desp_trabalho%>%
      filter(nivel_2==1)%>%
      mutate( exercicio = as.character(exercicio))%>%
      mutate(fase_despesa = coluna) %>%
      select(conta, valor,exercicio,fase_despesa, instituicao) %>%
      #mutate(instituicao = reorder(instituicao, valor)) %>%
      mutate(conta = reorder(conta, valor)) %>%
      filter(instituicao %in% instituicao_sel) %>%
      #top_n(10,valor) %>%
      ggplot(aes(x=conta, y= valor/10^6, fill=fase_despesa)) + #,
      geom_col( )+ #fill= "#329c2d"
      theme_light() +
      theme(
        #strip.text =  element_blank(),
        axis.text.x =  element_text(angle = 90, hjust = 1),
        panel.grid = element_blank()  )+
      labs(
        y = "Valor em R$ milhões",
        x=  NULL,
        fill = ""  )+
      scale_y_continuous(labels=function(x) format(x, big.mark = ".", scientific = FALSE))+
      scale_fill_viridis(discrete = TRUE)+
      facet_wrap(factor(exercicio)+instituicao~.) +
      coord_flip()
    
    return(graph)
    
  }
  
  if (opcao$topico==3){ #Despesas por função
    
    funcao<-
    (contas %>%
    filter(conta %in% opcao$funcao) %>%
    select(cod_interno))$cod_interno
    
    #print(funcao)
    
    if (opcao_uf){
      df_func <- rsiconfi::get_dca_mun_state(opcao$ano,"I-E",lista_instituicao,arg_cod_conta = funcao)
      
    } else{
      df_func <- rsiconfi::get_dca(opcao$ano,"I-E",lista_instituicao,arg_cod_conta = funcao)
      
    }
    
    
    
    instituicao_sel<-
    (df_func %>%
      group_by(instituicao) %>%
      summarise(
        valor = sum(valor)
      ) %>%
      top_n(10, valor))$instituicao

        
    #print(df_func)
    
    df_func %>%
      filter(coluna  %in% opcao$fase) %>%
      filter(instituicao %in% instituicao_sel) %>%
      ggplot(aes(x=conta, y= valor, fill= coluna)) +
      geom_col() +
      scale_fill_viridis(discrete=TRUE) +
      theme_light() +
      theme(
        #strip.text =  element_blank(),
        axis.text.x =  element_text(angle = 90, hjust = 1),
        panel.grid = element_blank()  )+
      labs(
        y = "Valor gasto na função",
        x=  NULL,
        fill = "Fase da despesa"  )+
      scale_y_continuous(labels=function(x) format(x, big.mark = ".", scientific = FALSE))+
      facet_wrap(exercicio+instituicao~.) +
      coord_flip()
    
    
  }
  
}

generate_dt <- function(opcao){
  
  lista_instituicao <- get_lista_instituicao(opcao)
  
  opcao_uf<- (opcao$tipo_cons_mun=="Todos de uma ou mais UFs" & opcao$escopo == "Municípios")
  
  if (opcao$topico ==1){
    
    if (opcao_uf){
      df_rec <- rsiconfi::get_dca_mun_state(opcao$ano,"I-C",lista_instituicao)
      
    } else{
      df_rec <- rsiconfi::get_dca(opcao$ano,"I-C",lista_instituicao)
      
    }
    
    return(df_rec)
  }
  
  if (opcao$topico ==2){
    if (opcao_uf){
      df_desp <- rsiconfi::get_dca_mun_state(opcao$ano,"I-D",lista_instituicao)
      
    } else{
      
      df_desp <- rsiconfi::get_dca(opcao$ano,"I-D",lista_instituicao)
      
    }
    
    
    df_desp <-
    df_desp%>%
      filter(coluna %in% opcao$fase)

    return(df_desp)
  }
  
  if (opcao$topico ==3){
    
    
    funcao<-
    (contas %>%
    filter(conta %in% opcao$funcao) %>%
    select(cod_interno))$cod_interno
    
    if (opcao_uf){
      df_func <- rsiconfi::get_dca_mun_state(opcao$ano,"I-E",lista_instituicao,arg_cod_conta = funcao)
      
    } else{
      
      df_func <- rsiconfi::get_dca(opcao$ano,"I-E",lista_instituicao,arg_cod_conta = funcao)
      
    }

    
    #print(funcao)
    
    df_func <- rsiconfi::get_dca(opcao$ano,"I-E",lista_instituicao,arg_cod_conta = funcao)
    df_func <-
    df_func%>%
      filter(coluna %in% opcao$fase)

    return(df_func)
  }
  
  
}

generate_script<- function(opcao){
  
  lines_script<- tibble(script="" )
  
  lines_script[1,1]<- '# install.packages("devtools")'
  lines_script[2,1]<- 'devtools::install_github("tchiluanda/rsiconfi")' 
  lines_script[3,1]<- 'library(rsiconfi)' 
  lines_script[4,1]<- "#get data using rsiconfi which is the package that consumes SICONFI API"
  
  lista_ano<- opcao$ano[1]
  
  opcao_uf <- (opcao$tipo_cons_mun=="Todos de uma ou mais UFs" & opcao$escopo == "Municípios")
  
  for (ano in opcao$ano[-1]){
    lista_ano<- paste(lista_ano,ano,sep = ",")
  }
  
  lista_fase<- paste0("'",opcao$fase[1], "'")
  for (fase in opcao$fase[-1]){
    lista_fase<- paste0(lista_fase,",","'", fase, "'")
  }
  
  lista_instituicao <- get_lista_instituicao(opcao)
  
  lista_instituicao_script<- paste0("'",lista_instituicao[1], "'")
  for (instituicao in lista_instituicao[-1]){
    lista_instituicao_script<- paste0(lista_instituicao_script,",","'", instituicao, "'")
  }
  
  
  funcao<-
    (contas %>%
       filter(conta %in% opcao$funcao) %>%
       select(cod_interno))$cod_interno
  
  
  
  lista_funcao<- paste0("'",funcao[1], "'")
  
  
  
  for (funcao in funcao[-1]){
    lista_funcao<- paste0(lista_funcao,",","'", funcao, "'")
  }
  
  
  
  if (opcao$topico ==1){
    
    if (opcao_uf){
      
      lines_script[5,1]<- paste0("df_rec <- rsiconfi::get_dca_mun_state(c(",lista_ano,"),'I-C',c(", lista_instituicao_script,"))")
      
      
    } else{
      
      lines_script[5,1]<- paste0("df_rec <- rsiconfi::get_dca(c(",lista_ano,"),'I-C',c(", lista_instituicao_script,"))")
      
      
      
    }
    
    
  }
  
  if (opcao$topico ==2){
    
    if (opcao_uf){
      
      lines_script[5,1]<- paste0("df_rec <- rsiconfi::get_dca_mun_state(c(",lista_ano,"),'I-D',c(", lista_instituicao_script,"))")
      
      
    } else{
      
      lines_script[5,1]<- paste0("df_rec <- rsiconfi::get_dca(c(",lista_ano,"),'I-D',c(", lista_instituicao_script,"))")
      
      
      
    }
    
    
    lines_script[6,1]<- "#Filter the data. Only the selected expenditure phases will be available"
    lines_script[7,1]<- paste0("df_desp <-df_desp%>%filter(coluna %in% c(",lista_fase,"))")
    
  }
  
  if (opcao$topico ==3){
    
    lines_script [5,1] <- "#Call the method that retrieves data for the specified government functions"
    
    if (opcao_uf){
      
      lines_script[6,1]<- paste0("df_func <- rsiconfi::get_dca_mun_state(c(",lista_ano,"),'I-E',c(", lista_instituicao_script,"),arg_cod_conta =c(", lista_funcao,"))")
      
      
    } else{
      
      lines_script[6,1]<- paste0("df_func <- rsiconfi::get_dca(c(",lista_ano,"),'I-E',c(", lista_instituicao_script,"),arg_cod_conta =c(", lista_funcao,"))")
      
      
      
    }
    
    

    lines_script[7,1]<- "#Filter the data. Only the selected expenditure phases will be available"
    lines_script[8,1]<- paste0("df_func <-df_func%>%filter(coluna %in% c(",lista_fase,"))")
    
  }
  
  
  
  lines_script
  
  
}

```

Inputs {.sidebar}
-------------------------------------

```{r}
radioButtons("topico",label = "Escolha o tipo de consulta", choices = unique(glossario_siconfi%>%
  select(topico))$topico, selected = (glossario_siconfi%>%
  select(topico))$topico[1])

useShinyjs(rmd = TRUE)

hidden(
         div(id = "ano", selectInput("ano", label ="Informe o ano", choices = 2018:2014, selected = 2018, multiple = TRUE)))

hidden(
  div(id = "periodicidade", radioButtons("periodicidade", label ="Informe a periodicidade", choices = c("Bimestral","Quadrimestral","Semestral", "Anual"), selected = "Anual"))
  
         )

hidden(
  div(id = "fase", checkboxGroupInput("fase", label ="Informe a fase da despesa", choices = c("Despesas Empenhadas", "Despesas Liquidadas","Despesas Pagas"), selected = "Despesas Liquidadas"))
  
         )

hidden(
         div(id = "funcao", selectInput("funcao", label ="Informe a função de governo", choices = unique(contas$conta), selected = c("10 - Saúde", "12 - Educação"), multiple = TRUE)))


hidden(
  div(id = "escopo", radioButtons("escopo", label ="Informe o escopo da consulta", choices = c("Governo Federal", "Estados","Municípios"), selected = "Governo Federal"))
  
         )

hidden(
         div(id = "uf", selectInput("uf", label ="Selecione uma ou mais UF", choices = sort((municipios_IBGE%>%filter(!is.na(cod_uf))%>%distinct(uf))$uf), selected = "SP", multiple = TRUE)))



hidden(
  div(id = "tipo_cons_mun", radioButtons("tipo_cons_mun", label ="Informe o filtro para municípios", choices = c("Escolher de uma lista", "Todos de uma ou mais UFs","Por Mesoregião", "Por faixa populacional - quartis", "Por faixa populacional - grupos ibge", "Por posição PIB per-capita", "Por posição PIB total", "Por principal atividade econômica", "Por agrupamento econômico" ), selected = "Escolher de uma lista"))
  
         )

hidden(
         div(id = "municipio", selectInput("municipio", label ="Selecione um ou mais municípios", choices = municipios_IBGE$nome_municipio, selected = "São Paulo", multiple = TRUE)))


hidden(
         div(id = "mun_uf", selectInput("mun_uf", label ="Selecione uma ou mais UF para filtrar os municípios", choices = sort((municipios_IBGE%>%filter(!is.na(cod_uf))%>%distinct(uf))$uf), selected = "RO", multiple = TRUE)))

hidden(
         div(id = "mun_meso", selectInput("mun_meso", label ="Selecione uma ou mais mesoregiões para filtrar os municípios", choices = get_lista_mesoregioes(), selected = "Metropolitana de São Paulo", multiple = TRUE)))

hidden(
         div(id = "mun_pib_pc", sliderInput("mun_pib_pc", label ="Selecione uma faixa de posições", min= 1, max= NROW(ibge_pib_mun), step = 100,value = c(0,100))))

hidden(
         div(id = "mun_pib_total", sliderInput("mun_pib_total", label ="Selecione uma faixa de posições", min= 1, max= NROW(ibge_pib_mun), step = 100,value = c(0,100))))


hidden(
         div(id = "mun_atv_eco", checkboxGroupInput("mun_atv_eco", label ="Selecione uma ou mais atividades econômicas", choices = get_lista_atividades(), selected = get_lista_atividades()[1])))


hidden(
         div(id = "mun_grp_eco", selectInput("mun_grp_eco", label ="Selecione um município do agrupamento econômico", choices = municipios_IBGE$nome_municipio, selected = "São Paulo")))


hidden(
  div(id = "mun_pop", checkboxGroupInput("mun_pop", label ="Selecione uma ou mais faixas populacionais", choices = c("Primeiro quartil", "Segundo quartil","Terceiro quartil", "Quarto quartil"), selected = "Quarto quartil"))
  
         )


hidden(
  div(id = "mun_pop_faixa", checkboxGroupInput("mun_pop_faixa", label ="Selecione uma ou mais faixas populacionais", choices =faixas_ibge , selected = faixas_ibge[8])
           ))



hidden(
         div(id = "fim", textInput("fim", "Fim", value = "Obrigado por usar a nossa interface.", width = NULL,
   placeholder = NULL)))


hidden( div(id = "finalizar",actionButton("finalizar", "Finalizar")))

hidden(
         div(id = "state", textInput("state", "estado", value = "1", width = NULL,
   placeholder = NULL)))


hidden(
         div(id = "fl_grafico", textInput("fl_grafico", "fl_grafico", value = "1", width = NULL,
   placeholder = NULL)))

hidden(
         div(id = "fl_dado", textInput("fl_dado", "fl_dado", value = "1", width = NULL,
   placeholder = NULL)))


hidden(
         div(id = "anterior", actionButton("anterior", "Anterior", width = '100%')))


hidden(
         div(id = "finalizar", actionButton("finalizar", "Finalizar", width = '100%')))




div(id = "proximo", actionButton("proximo", "Próximo", width = '100%'))
div(id = "grafico", actionButton("grafico", "Gera Gráfico", width = '100%'))
div(id = "dados", actionButton("dados", "Gera Dados", width = '100%'))





```

```{r}
#actionButton("proximo", "Próximo")


observeEvent(input$proximo, {
  

  set_next_state(input$state, "P")
  

})


observeEvent(input$anterior, {
  
  set_next_state(input$state, "A")
  

})

observeEvent(input$grafico, {
  
  show_graph<<-TRUE
  
  
  updateTextInput(session,"fl_grafico",value=1)

  

})


observeEvent(input$dados, {
  
  show_data<<- TRUE
  
  updateTextInput(session,"fl_dado",value=1)
  
  

})




observeEvent(input$ano,{
  
  print("observeEvent(input$ano")
  
  show_graph<<-FALSE
  show_data<<- FALSE

  updateTextInput(session,"fl_grafico",value=0)
  updateTextInput(session,"fl_dado",value=0)

})


observeEvent(input$fase,{
  
  print("observeEvent(input$fase")
  
  show_graph<<-FALSE
  show_data<<- FALSE

  updateTextInput(session,"fl_grafico",value=0)
  updateTextInput(session,"fl_dado",value=0)

})


observeEvent(input$funcao,{
  
  print("observeEvent(input$funcao")
  show_graph<<-FALSE
  show_data<<- FALSE

  updateTextInput(session,"fl_grafico",value=0)
  updateTextInput(session,"fl_dado",value=0)

})


observeEvent(input$uf,{
  
  print("observeEvent(input$uf")
  show_graph<<-FALSE
  show_data<<- FALSE

  updateTextInput(session,"fl_grafico",value=0)
  updateTextInput(session,"fl_dado",value=0)

})



observeEvent(input$tipo_cons_mun,{
  
  print("observeEvent(input$tipo_cons_mun")
  show_graph<<-FALSE
  show_data<<- FALSE

  updateTextInput(session,"fl_grafico",value=0)
  updateTextInput(session,"fl_dado",value=0)

})


observeEvent(input$municipio,{
  
  print("observeEvent(input$municipio")
  
  show_graph<<-FALSE
  show_data<<- FALSE

  updateTextInput(session,"fl_grafico",value=0)
  updateTextInput(session,"fl_dado",value=0)

})


observeEvent(input$mun_uf,{
  
  print("observeEvent(input$mun_uf")
  
  show_graph<<-FALSE
  show_data<<- FALSE

  updateTextInput(session,"fl_grafico",value=0)
  updateTextInput(session,"fl_dado",value=0)

})


observeEvent(input$mun_pop,{
  
  print("observeEvent(input$mun_pop")
  
  show_graph<<-FALSE
  show_data<<- FALSE

  updateTextInput(session,"fl_grafico",value=0)
  updateTextInput(session,"fl_dado",value=0)

})

```



Column {data-width=200}
-----------------------------------------------------------------------

### Instruções


```{r}
shiny::renderUI({
  

  instrucoes_trabalho<- 
    instrucoes%>%
    filter(estado==input$state)%>%
  select(instrucoes)
    


    HTML(
        
        kable(instrucoes_trabalho, col.names = "")
    )
})

```


### Sobre a sua escolha

```{r}
shiny::renderUI({
  

  
  glossario_trabalho<- 
    glossario_siconfi%>%
    filter(topico==input$topico) %>%
    select(explicacao)
    


    HTML(
        
        kable(glossario_trabalho, col.names = "")
    )
})



```


Column {.tabset .tabset-fade}
-----------------------------------------------------------------------

### Script que gera os dados

```{r}
library(DT)


renderDataTable({

  id_topico<<-
    (glossario_siconfi%>%
       filter(topico==input$topico)%>%
       select(id))$id[1]
  
  id_opcao<- list(topico = id_topico, 
                  ano= input$ano, 
                  fase = input$fase, 
                  funcao= input$funcao, 
                  escopo = input$escopo,
                  uf = input$uf,
                  tipo_cons_mun = input$tipo_cons_mun,
                  municipio = input$municipio,
                  mun_uf = input$mun_uf,
                  mun_pop = input$mun_pop,
                  mun_pop_faixa = input$mun_pop_faixa,
                  mun_meso = input$mun_meso,
                  mun_pib_pc = input$mun_pib_pc,
                  mun_pib_total = input$mun_pib_total,
                  mun_atv_eco = input$mun_atv_eco,
                  mun_grp_eco = input$mun_grp_eco
                  )
  
  script<- generate_script(id_opcao)
  
  print("input$fl_grafico")
  print(input$fl_grafico)
  
  # updateTextInput(session, "fl_grafico", value = 1)
  # show_graph<<-TRUE
  # 
  # updateTextInput(session, "fl_dado", value = 1)
  # show_data<<-TRUE
  
  
  DT::datatable(
    script,
    class = "",
    rownames = FALSE,
    fillContainer = TRUE,
    selection = c("none"),
    extensions = 'Buttons', options = list(
       ordering=FALSE,
       paging=FALSE,
       searching= FALSE,
       info = FALSE,
       pageLength = NROW(script),
       dom = 'Bfrtip',
       buttons = c('copy')
    )
  )%>%
    formatStyle( columns = "script",backgroundColor = '#f5f5f5')
  
  
})



```



### Gráfico com dados da seleção

```{r}


renderPlot({
  print("show_graph")
  print(show_graph)
  
  if (input$fl_grafico == 1 && show_graph){
    id_topico<-
      (glossario_siconfi%>%
         filter(topico==input$topico)%>%
         select(id))$id[1]
    
    id_opcao<- list(topico = id_topico, 
                    ano= input$ano, 
                    fase = input$fase, 
                    funcao= input$funcao, 
                    escopo = input$escopo,
                    uf = input$uf,
                    tipo_cons_mun = input$tipo_cons_mun,
                    municipio = input$municipio,
                    mun_uf = input$mun_uf,
                    mun_pop = input$mun_pop,
                    mun_pop_faixa = input$mun_pop_faixa,
                  mun_meso = input$mun_meso,
                  mun_pib_pc = input$mun_pib_pc,
                  mun_pib_total = input$mun_pib_total,
                  mun_atv_eco = input$mun_atv_eco,
                  mun_grp_eco = input$mun_grp_eco
    )
    
    
    
    graph<<-generate_graph(id_opcao)
    
    
    
    graph
    
    
  }
  
  
  
})


```

### Dados brutos da seleção

```{r}
library(DT)


renderDataTable({
  
  
  
  if (input$fl_dado == 1 && show_data){
    
    id_topico<<-
      (glossario_siconfi%>%
         filter(topico==input$topico)%>%
         select(id))$id[1]
    
    id_opcao<- list(topico = id_topico, 
                    ano= input$ano, 
                    fase = input$fase, 
                    funcao= input$funcao, 
                    escopo = input$escopo,
                    uf = input$uf,
                    tipo_cons_mun = input$tipo_cons_mun,
                    municipio = input$municipio,
                    mun_uf = input$mun_uf,
                    mun_pop = input$mun_pop,
                    mun_pop_faixa = input$mun_pop_faixa,
                    mun_meso = input$mun_meso,
                  mun_pib_pc = input$mun_pib_pc,
                  mun_pib_total=  input$mun_pib_total,
                  mun_atv_eco = input$mun_atv_eco,
                  mun_grp_eco = input$mun_grp_eco
    )
    
    raw_data<<- generate_dt(id_opcao)
    
    
    
    DT::datatable(
      raw_data,
      rownames = FALSE,
      fillContainer = TRUE,
      selection = c("none"),
      
      extensions = 'Buttons', options = list(
        pageLength = NROW(raw_data),
        dom = 'Bfrtip',
        buttons = c('copy', 'csv', 'excel', 'pdf', 'print')
      )
    )
    
    
  }
  
  
  
})

```


